name: get_bilibili_api

# Controls when the workflow will run
on:
  push:
  schedule:
    - cron: '0 0 1 * *'
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        BASE_URL: /

    steps:
    - uses: actions/checkout@v2
    - name: Clone
      run: git clone -b main https://github.com/Nemo2011/bilibili-api.git ./bilibili-api
    - name: Move2
      run: mv ./bilibili-api/bilibili-api/data ./data
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        branch: main # The branch the action should deploy to.
        folder: .