name: get_bilibili_api

# Controls when the workflow will run
on:
  push:
  schedule:
    - cron: '0 0 1 * *'
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        BASE_URL: /

    steps:
    - uses: actions/checkout@v2
    - name: Mkdir1
      run: mkdir ./data
    - name: Mkdir2
      run: mkdir ./deploy
    - name: Copy
      run: ls | grep -v '^\(\.\{1,2\}\|deploy\)$' | xargs cp -at deploy
    - name: Clone
      run: git clone -b dev https://github.com/Nemo2011/bilibili-api.git
    - name: Move
      run: cp -r ./bilibili-api/bilibili_api/data ./deploy/data
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        branch: main # The branch the action should deploy to.
        folder: ./deploy